##### Q1. 
Write a code to obtain a positive integer as the input, and spell the number digit-by-digit. For example, if the input is 4503, your code should print "four five zero three".

In [1]:
x = [int(i) for i in input("ENTER a number: ")]

dict1 = {
    0:"zero", 1:"one", 2:"two", 3:"three", 4:"four",
    5:"five", 6:"six", 7:"seven", 8:"eight", 9:"nine"
}

for i in x:
    print(dict1[i], end=" ")

##### Q2

Write a code to compute the greatest common factor and the least common multiple of two numbers.

In [1]:
#HCF
def HCF(a,b):
    if a<b :
        a,b = b,a
        
    if b == 0:
        return a

    return HCF(a-b,b)
    
a,b = (int(x) for x in input("Enter Two Number").split())

x = HCF(a,b)

print("GCF of {} and {} is {}".format(a,b,x))
print("LCM of {} and {} is {}".format(a,b,a*b//x))

GCF of 1 and 2 is 1
LCM of 1 and 2 is 2


##### Q3

Write a code to compute all the saddle points of a given matrix along with the locations in the matrix. Recall that a saddle point is an element of a matrix that is simultaneously the maximum of a row and the minimum of a column, or the minimum of a row and the maximum of a column.


In [36]:
import numpy as np

m = np.random.randint(1,11)
n = np.random.randint(1,11)
A = np.random.randint(0,11, (m,n))

print(A)

rowwise_maxima =set()
rowwise_minima =set()
for i in range(m):
    x1 = A[i,:].max()
    li1 = np.where(A[i,:]==x1)[0]
    
    x2 = A[i,:].min()
    li2 = np.where(A[i,:]==x2)[0]
    
    for ele in li1:
        rowwise_maxima.add((i,ele))
    for ele in li2:
        rowwise_minima.add((i,ele))

columnwise_maxima =set()
columnwise_minima =set()
for j in range(n):
    x1 = A[:,j].max()
    li1 = np.where(A[:,j]==x1)[0]
    
    x2 = A[:,j].min()
    li2 = np.where(A[:,j]==x2)[0]
    
    for ele in li1:
        columnwise_maxima.add((ele,j))
    for ele in li2:
        columnwise_minima.add((ele,j))

print(rowwise_maxima.intersection(columnwise_minima))
print(rowwise_minima.intersection(columnwise_maxima))

[[ 6 10]]
{(0, 1)}
{(0, 0)}


Q4

In [60]:
import numpy as np

m = np.random.randint(1,11)
n = np.random.randint(1,11)

a = np.random.randint(0,11,m)
b = np.random.randint(0,11,n)

print(np.poly1d(a),"\n\n",np.poly1d(b))

np.polymul(a,b)

   9     8     7     6     5     3
5 x + 8 x + 3 x + 1 x + 1 x + 3 x + 1 x + 6 

    9     8     6     5     2
1 x + 9 x + 1 x + 6 x + 2 x + 8 x + 9


array([  5,  53,  75,  33,  48,  60,  22,  44,  63, 133, 170,  38,  29,
        51,  24,  29,  20,  57,  54])

Q5

In [68]:
import numpy as np

m = np.random.randint(1,11)
a = np.random.randint(0,11,m)
print(a)

a = np.sort(a)
print(a)
print(a[::-1])

[ 6  6  5  1  9 10  9 10  8]
[ 1  5  6  6  8  9  9 10 10]
[10 10  9  9  8  6  6  5  1]


Q6

In [185]:
import numpy as np

def RREF (A):
    m,n = A.shape
    det = 1
    for i in range(m):
        #index of first non zero element
        x = np.nonzero(A[i,:])[0]
        if x.size == 0:
            continue
        first_nonzeroElement_index = x[0]
        
        det = det * A[i,first_nonzeroElement_index]
        
        A[i,:] = A[i,:]/A[i,first_nonzeroElement_index]
        
        for k in range(i+1,m):
            if A[k,:][first_nonzeroElement_index] == 0:
                continue
            
            A[k,:] = A[k,:] - A[k,:][first_nonzeroElement_index]*A[i,:]
    
    return A,det
    
m = np.random.randint(1,11)
n = np.random.randint(1,11)

A = np.random.randint(1,11,(m,n))

A = A.astype(float)

print("The original Matrix:\n\n",A,"\n\n")

print("The RREF matrix:\n")

RREF_matrix,det = RREF(A.copy())

for x in RREF_matrix.round(3):
    print(x)

if m==n:
    print("The determinant of the matrix: ", det)
    
    print("The determinant of the matrix: ", np.linalg.det(A))

#print(RREF(A))

The original Matrix:

 [[ 8.  2.]
 [ 3.  2.]
 [ 3.  4.]
 [ 5.  5.]
 [ 9.  3.]
 [ 8.  4.]
 [ 6.  6.]
 [ 2.  5.]
 [ 6.  5.]
 [ 7. 10.]] 


The RREF matrix:

[1.   0.25]
[0. 1.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]


In [168]:
A.dtype == 'float64'

True